# Generated by Django 6.0.4 on 2026-04-25 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('year_built', models.CharField(blank=True, max_length=50, verbose_name='Год постройки')),
                ('total_area', models.FloatField(blank=True, null=True, verbose_name='Площадь, м²')),
                ('floors', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало')),
                ('end_datetime', models.DateTimeField(verbose_name='Окончание')),
                ('participants_count', models.IntegerField(verbose_name='Количество участников')),
                ('equipment_needed', models.TextField(blank=True, verbose_name='Необходимое оборудование')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Особые требования')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('rejected', 'Отклонено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Приоритетное бронирование')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('booking_created', 'Создание бронирования'), ('booking_confirmed', 'Подтверждение бронирования'), ('booking_cancelled', 'Отмена бронирования'), ('booking_rejected', 'Отклонение бронирования'), ('user_login', 'Вход пользователя')], max_length=50, verbose_name='Тип события')),
                ('description', models.TextField(verbose_name='Описание')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.booking', verbose_name='Бронирование')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название помещения')),
                ('venue_type', models.CharField(choices=[('hall', 'Актовый зал'), ('conference', 'Конференц-зал'), ('sport', 'Спортивный зал'), ('rest', 'Комната отдыха'), ('other', 'Иное помещение')], default='hall', max_length=20, verbose_name='Тип помещения')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь, м²')),
                ('capacity', models.IntegerField(verbose_name='Вместимость (чел.)')),
                ('equipment', models.TextField(blank=True, verbose_name='Оборудование')),
                ('special_conditions', models.TextField(blank=True, verbose_name='Особые условия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно для бронирования')),
                ('work_start', models.TimeField(default='08:00', verbose_name='Начало работы')),
                ('work_end', models.TimeField(default='20:00', verbose_name='Конец работы')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за час (руб.)')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Фото (URL)')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='rental.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rental.venue', verbose_name='Помещение'),
        ),
    ]
